name: CI
on: [push, pull_request]
jobs:
  linux-x64:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cc: [gcc, clang]
    steps:
      - uses: actions/checkout@v6
      - run: sudo apt-get install -y libffi-dev
      - run: ${{ matrix.cc }} build.c -o build && ./build -b Bin
      - run: ./build test -- --multithreaded --force-colors

  linux-arm:
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        cc: [gcc, clang]
    steps:
      - uses: actions/checkout@v6
      - run: sudo apt-get install -y libffi-dev
      - run: ${{ matrix.cc }} build.c -o build && ./build -b Bin
      - run: ./build test -- --multithreaded --force-colors
  windows-x64:
    runs-on: windows-latest
    strategy:
      matrix:
        cc: [cl, clang, clang-cl]
    defaults:
      run:
        shell: cmd
    steps:
      - uses: actions/checkout@v6
      - run: call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat" && cl /std:c11 /Zc:preprocessor build.c /Fe:build.exe && build.exe -b Bin && build.exe BCC=${{ matrix.cc }} HCC=${{ matrix.cc }} test -- --multithreaded --force-colors
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - run: cc build.c -o build && ./build -b Bin
      - run: ./build test -- --multithreaded --force-colors
